### PR TITLE
Bump github.com/fujiwara/tfstate-lookup

### PR DESCRIPTION
**Pull request by jkroepke**
Bumping fujiwara/tfstate-lookup which contains the following PR:

* https://github.com/fujiwara/tfstate-lookup/pull/86

I would like to use helmfile with terraform states in my CI chain. At the moment, tfstate-lookup has dependency agaist a configured .terraform/tfstate.json OR a working Azure CLI.

By using azidentity package from the Azure SDK, environment variables can be used for authentication. vals is using the same mechansim for connect against Azure KeyVaults.

https://github.com/helmfile/vals/blob/8d1b03eb6d035ec7f7106665ead0aa3b985547ed/pkg/azureclicompat/workload.go#L44

What I have run:

```
go get -u github.com/fujiwara/tfstate-lookup
go mod tidy
```

and code fixes from API changes.

I would much appreciate it, if there could be a new release for vals after this merge, since I have to create PR on helmfile which bumps the vals dependency.

---

I have tested this PR locally on my machine

```
# Auth by CLI
$ az login
$ ./vals get ref+tfstateazurerm://rg-terraform-prd-euw/stterraformprdeuw/tfstate/sub-shared-prd-euw-01/level0/terraform.tfstate/output.rsv_rg_name
rg-shared-prd-euw%

# Auth by env
$ az account clear
$ export AZURE_TENANT_ID=...
$ export AZURE_SUBSCRIPTION_ID=...
$ export AZURE_CLIENT_SECRET=...
$ export AZURE_CLIENT_ID=...

$ ./vals get ref+tfstateazurerm://rg-terraform-prd-euw/stterraformprdeuw/tfstate/sub-shared-prd-euw-01/level0/terraform.tfstate/output.rsv_rg_name
rg-shared-prd-euw%
```

### CODE REVIEW

**Comment by jkroepke** [comment]
Additionally mute a warning, since it seems related to `github.com/hashicorp/vault/api`, but I'm not touching anythink around it

Link to golangci warning: https://github.com/helmfile/vals/actions/runs/4607590746

**Comment by yxxhero** [comment]
@jkroepke Thanks for your PR.

**Comment by yxxhero** [comment]
@jkroepke I will release a new version asap after https://github.com/helmfile/vals/pull/129 be merged. then you can post a new PR for helmfile.

**Comment by jkroepke** [comment]
@yxxhero Thanks for your work and for the clarification!

**Pull request merged**
