### PR TITLE
feat(providers): add support for GCP KMS

### PR DESCRIPTION
**Pull request by ruanda**
Add support for GCP KMS. Tested locally.

### CODE REVIEW

**Comment by yxxhero** [comment]
@ruanda please fix lint error.

**Comment by yxxhero** [comment]
@ruanda please add some unit tests.

**Comment by ruanda** [comment]
@mumoshu Sure, I will work on that

**Review by mumoshu — APPROVED** [review]
Awesome! Thank you very much for your contribution @ruanda ☺️

**Pull request merged**
