### PR TITLE
Feat/conjur

### PR DESCRIPTION
**Pull request by antoinemiquel**
Hello, 
this request proposes a new provider for the Cyberark-Conjur secret manager.
I am at your disposal for any modification

### CODE REVIEW

**Comment by yxxhero** [comment]
@antoinemiquel please add some tests.

**Comment by antoinemiquel** [comment]
@yxxhero ok thanks, I'm working on it

**Comment by yxxhero** [comment]
@antoinemiquel I enable unit-tests. please rebase your code.

**Comment by antoinemiquel** [comment]
@yxxhero Thanks for the merge !! :-)

**Pull request merged**
