### PR TITLE
replace all mozilla/sops with getsops/sops

### PR DESCRIPTION
**Pull request by lucasfcnunes**
Refs: https://github.com/getsops/sops/issues/1246

### CODE REVIEW

**Comment by lucasfcnunes** [comment]
After this I want to bump the sops 3.7.3 (1+ year old, 173 commit, https://github.com/getsops/sops/compare/v3.7.3...v3.8.0) to 3.8.0

**Comment by yxxhero** [comment]
@lucasfcnunes please run `go mod tidy` locally.

**Comment by lucasfcnunes** [comment]
@yxxhero doing it rn

**Comment by lucasfcnunes** [comment]
[Bump to 3.8.0](https://github.com/helmfile/vals/pull/168/commits/05373fa3cecfa6613fe960b927eb2f2263546209) because of: `module go.mozilla.org/sops/v3` @ https://github.com/getsops/sops/blob/v3.7.3/go.mod#L1
Causing:
```sh
$ go mod tidy
go: github.com/getsops/sops/v3@v3.7.3: parsing go.mod:
        module declares its path as: go.mozilla.org/sops/v3
                but was required as: github.com/getsops/sops/v3
```
---
Closes https://github.com/helmfile/vals/pull/169

**Comment by lucasfcnunes** [comment]
@yxxhero could you approve the pending workflows?

**Comment by lucasfcnunes** [comment]
Guess I'll fix `google.golang.org/genproto/googleapis/cloud/secretmanager/v1` in another PR and then rebase here.

**Comment by lucasfcnunes** [comment]
@yxxhero could you reopen?

**Comment by yxxhero** [comment]
@lucasfcnunes no. please post a new PR. thanks.

**Pull request closed without merging**
