### PR TITLE
fix empty yaml on documents with comment only sections

### PR DESCRIPTION
**Pull request by alstephenclaypool**
Attempt at a fix on the issue I raised in https://github.com/helmfile/vals/issues/165

I'm not sure if this is too heavy of an approach or not, but found that it worked for what I was running into and figured I would propose it.

### CODE REVIEW

**Comment by yxxhero** [comment]
@alstephenclaypool please fix DCO issue.

**Comment by yxxhero** [comment]
@alstephenclaypool thanks for your PR. could you add some tests for this case?

**Comment by alstephenclaypool** [comment]
> @alstephenclaypool thanks for your PR. could you add some tests for this case?

Sure, I've just pushed those to the PR, let me know if there are any other cases you'd like me to add.

**Comment by yxxhero** [comment]
@alstephenclaypool thanks so much.

**Pull request merged**
