### PR TITLE
Add redis provider

### PR DESCRIPTION
**Pull request by ibice**
Related to #147

### CODE REVIEW

**Comment by mumoshu** [comment]
@ibice Thanks for your contribution! My quick review says code LGTM!

Before going forward, would you let me know the rationale behind using Redis as the secrets store?

Is it any better than using a general-purpose database like MySQLL as a secrets manager, which won't be a very good idea because it seems to have no security features like advanced data encryption and/or per-key audit logs?

**Comment by ibice** [comment]
Hi @mumoshu, thank you for your review!

I cannot think of good reasons to use Redis as a secrets store, I never investigated that use case and I wouldn't be surprised if it's considered a bad practice. In my case, Redis is used as (non-secret) configuration database, for values like replica numbers.

**Comment by mumoshu** [comment]
@ibice Thank you so much for clarifying! Using it as a parameter store does make sense.

Would you also mind telling me why those parameters aren't directly coded into a configuration file?!

I thought you could simplify it by moving the parameters you currently store in Redis into e.g. Helm or Helmfile values.yaml files or K8s ConfigMap, or even `env` under the K8s pod spec.

**Comment by ibice** [comment]
I assume this doesn't add value. I'm going to close the PR so it doesn't clutter your repo. Thanks for everything!

**Pull request closed without merging**
