### PR TITLE
Upgrading SOPS to 3.8.0

### PR DESCRIPTION
**Pull request by reegnz**
SOPS got moved to the CNCF.

The old module path cannot be used anymore, the tidy message is clear on
this:

```
❯ go mod tidy
go: go.mozilla.org/sops/v3@v3.8.0: parsing go.mod:
	module declares its path as: github.com/getsops/sops/v3
	        but was required as: go.mozilla.org/sops/v3
```

So I changed the module name and ran go mod tidy.

Signed-off-by: Zoltán Reegn <zoltan.reegn@gmail.com>

### CODE REVIEW

**Comment by reegnz** [comment]
Release notes: https://github.com/getsops/sops/releases/tag/v3.8.0

**Comment by yxxhero** [comment]
@reegnz please fix lint error.

**Comment by lucasfcnunes** [comment]
Duplicate of #168

**Comment by reegnz** [comment]
Sorry @lucasfcnunes your PR missed my attention. Thanks for fixing the google sdk deprecation though!

@yxxhero the fix in #171 is supposed to have fixed the linter errors.

**Comment by lucasfcnunes** [comment]
@yxxhero use this PR jnstead of mine.

**Pull request merged**
