### PR TITLE
Update tfstate-lookup and remove Workload Identity hack

### PR DESCRIPTION
**Pull request by jkroepke**
Hi, 

since azure/azidentity v1.3.0, Workload Identity is natively supported.

And we need azidentity 1.3.1 in our environment, since we recently introduce OIDC based logins.

See also: [docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect)

I already bump die dependency in https://github.com/fujiwara/tfstate-lookup/pull/133 and I would like to request it library bump in vals too.

I would also like to see an release of vals, because I have also raise an upgrade request in helmfiile.

### CODE REVIEW

**Comment by yxxhero** [comment]
@jkroepke @mumoshu  maybe is this a break change?

**Comment by mumoshu** [comment]
@yxxhero Probably it's just that the workload identity thing is done by the new azure-sdk and we don't need our own hack for the same thing, i.e. it isn't a breaking change?

**Comment by yxxhero** [comment]
@mumoshu yeah. make sense. I got. thanks so much.

**Review by yxxhero — APPROVED** [review]

**Comment by jkroepke** [comment]
So Fast! Thanks a lot!

**Pull request merged**
