### PR TITLE
feat(providers): first implementation of Doppler

### PR DESCRIPTION
**Pull request by carnei-ro**
Closes https://github.com/helmfile/vals/issues/173

### CODE REVIEW

**Comment by yxxhero** [comment]
@carnei-ro please fix conflicts.

**Comment by carnei-ro** [comment]
@yxxhero PR rebased. Thanks for the heads-up.

**Comment by yxxhero** [comment]
@carnei-ro could you test it locally?

**Comment by carnei-ro** [comment]
with doppler CLI:
```bash
$ DOPPLER_TOKEN=dp.st.production.Nu8.... doppler secrets
┌─────────────────────┬───────────────────────────────────────────────────────────────────────┬──────┐
│ NAME                │ VALUE                                                                 │ NOTE │
├─────────────────────┼───────────────────────────────────────────────────────────────────────┼──────┤
│ BAZ                 │ qux                                                                   │      │
│ DOPPLER_CONFIG      │ production                                                            │      │
│ DOPPLER_ENVIRONMENT │ production                                                            │      │
│ DOPPLER_PROJECT     │ delete-me                                                             │      │
│ FOO                 │ bar                                                                   │      │
│ MY_JSON_SECRET      │ {"some_string":"value", "some_number": 42,"some_list": ["apple","pine │      │
│                     │ apple"],"some_object":{"key_object_1":"val1","k2":"v2"},"some_bool":t │      │
│                     │ rue,"another_bool":false}                                             │      │
└─────────────────────┴───────────────────────────────────────────────────────────────────────┴──────┘
```

with `vals`:

`doppler-test.yml`:
```yaml
all_secrets: ref+doppler:////
all_secrets_explicit_project_and_environment: ref+doppler://delete-me/production/
another_secret: ref+doppler://delete-me/production/BAZ
all_secrets_with_doppler_envs: ref+doppler://delete-me/production/?include_doppler_defaults=true
some_json_secret: ref+doppler://delete-me/production/MY_JSON_SECRET
some_secret: ref+doppler://delete-me/production/FOO
```

```bash
$ DOPPLER_TOKEN=dp.st.production.Nu8... bin/vals eval -f doppler-test.yml 

all_secrets: '{"BAZ":"qux","FOO":"bar","MY_JSON_SECRET":"{\"some_string\":\"value\", \"some_number\": 42,\"some_list\": [\"apple\",\"pineapple\"],\"some_object\":{\"key_object_1\":\"val1\",\"k2\":\"v2\"},\"some_bool\":true,\"another_bool\":false}"}'
all_secrets_explicit_project_and_environment: '{"BAZ":"qux","FOO":"bar","MY_JSON_SECRET":"{\"some_string\":\"value\", \"some_number\": 42,\"some_list\": [\"apple\",\"pineapple\"],\"some_object\":{\"key_object_1\":\"val1\",\"k2\":\"v2\"},\"some_bool\":true,\"another_bool\":false}"}'
all_secrets_with_doppler_envs: '{"BAZ":"qux","DOPPLER_CONFIG":"production","DOPPLER_ENVIRONMENT":"production","DOPPLER_PROJECT":"delete-me","FOO":"bar","MY_JSON_SECRET":"{\"some_string\":\"value\", \"some_number\": 42,\"some_list\": [\"apple\",\"pineapple\"],\"some_object\":{\"key_object_1\":\"val1\",\"k2\":\"v2\"},\"some_bool\":true,\"another_bool\":false}"}'
another_secret: qux
some_json_secret: '{"some_string":"value", "some_number": 42,"some_list": ["apple","pineapple"],"some_object":{"key_object_1":"val1","k2":"v2"},"some_bool":true,"another_bool":false}'
some_secret: bar
```

**Pull request merged**
